spring.application.name=LastSys
spring.datasource.url="본인 sql주소"
spring.datasource.username=root
spring.datasource.password="mysql 비밀번호"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
