spring.application.name=Plia
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.datasource.url=jdbc:postgresql://localhost:5432/lastsys
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.no-store=true

kakao.maps.javascript-key=${KAKAO_MAPS_JAVASCRIPT_KEY:}
